version: '3.8'
services: 
  api: 
    build: 
      context: ./api
    container_name: api
    image: 733997234712.dkr.ecr.us-east-1.amazonaws.com/app-api
    ports: 
      - "3000:3000"
  ui: 
    build: 
      context: ./ui
    container_name: ui
    image: 733997234712.dkr.ecr.us-east-1.amazonaws.com/app-ui
    ports: 
      - "4200:4200"
  nginx: 
    build:
      context: ./nginx
    container_name: nginx
    depends_on: 
      - ui
      - api
    image: 733997234712.dkr.ecr.us-east-1.amazonaws.com/app-nginx
    ports: 
      - "80:80"
    
